FORMAT: 1A
HOST: https://api.packethost.net/v1

# Packet API (Private)

This is the Private API for Packet. Only internal Packet apps, like the portal
and mobile apps, can access these methods.

## Group Authentication

Authentication is done in the same way as in the public API; you do not need to
do anything special to access the private API. Access to the private API is 
determined by the `X-Consumer-Token` header.

See [the public API docs](http://localhost:8000/#page:authentication) for more 
information.
