# Group Invoices
Packet staff can mark invoices as paid manually. This is useful when a client
pays with some method other that an automatic charging of their card, like
check or cash.

## Invoice [/invoice/{id}]

+ Model

        {
          "id": "8421787b-739b-4bdb-861a-ffb8ac03c574",
          "href": "https://api.packethost.net/invoices/8421787b-739b-4bdb-861a-ffb8ac03c574",
          "amount": 150,
          "due_on": "2014-12-31",
          "created_at": "2014-12-04T12:00:00Z",
          "updated_at": "2014-12-15T12:00:00Z",
          "paid_at": "2014-12-15T12:00:00Z",
          "via": "check",
          "details": { "check_number": 1001, "bank": "Chase" },
          "project": {
            "href": "https://api.packethost.net/projects/0d96723f-95b6-42fe-8db4-cfdd4b17a3f7"
          }
        }

### Update an Invoice [PATCH]
Updates an invoices.

The details object in the request can be anything you'd like to track with the
payment.

+ Request

  + Body

            {
              "paid_at": "2014-12-04T12:00:00Z",
              "via": "check",
              "details": { "check_number": 1001, "bank": "Chase" }
            }

+ Response 200

  [Invoice][]

+ Response 422
