module.exports = function(grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    aglio: {
      packet: {
        files: {
          "web/index.html": [ "docs/*.md" ]
        },
        theme: "flatly-multi",
        seperator: "\n"
      }
    },

    connect: {
      packet: {
        port: 3000,
        base: './web'
      }
    }
  });

  grunt.loadNpmTasks('grunt-aglio');
  grunt.loadNpmTasks('grunt-connect');

  grunt.registerTask('reset', 'Clean up files generated by our compile process.', function() {
    grunt.file.delete('web/index.html');
  });
  grunt.registerTask('compile', ['aglio:packet']);
  grunt.registerTask('server', ['compile', 'connect:packet']);

  grunt.registerTask('default', ['server']);
};
