#!/usr/bin/env sh

docs_dir="$(realpath "$(dirname "$0")/../docs")"

for docset_dir in $docs_dir/*; do
  counter=0
  for file in $docset_dir/*.apib; do
    printf -v prefix_str '%03d' "$((counter++))"
    base="${file%.*}"
    filenameroot="${base#*-}"
    newname="$docset_dir/$prefix_str-$filenameroot.apib"

    if [ $file != $newname ]; then mv "$file" "$newname"; fi
  done
done
