# Group Projects
Projects are a way to group devices and grant users access to them.

## Projects [/projects]
A collection of projects that the current user is a member of.

### Retrieve all Projects [GET]
Returns a list of the current user's projects.

+ Response 200

  + Body

            {
              "projects": [
                {
                  "href": "https://api.packethost.net/projects/739ff9c9-0834-44c8-bba6-6a71b9a96783",
                  "id": "739ff9c9-0834-44c8-bba6-6a71b9a96783",
                  "name": "A Test Project",
                  ...
                },
                {
                  "href": "https://api.packethost.net/projects/74e70cdd-b51d-4d69-bf0c-ccf920643d7a",
                  "id": "74e70cdd-b51d-4d69-bf0c-ccf920643d7a",
                  "name": "My Second Project",
                  ...
                },
                ...
              ]
            }

### Create a Project [POST]
Creates a new projects and adds the current user as a member.

+ Request

  + Body

            {
              "name": "My New Project",
              "payment_method": "eedbb692-b217-477f-bfe5-8dd58df1cd09" // optional
            }

+ Response 201

  + Headers

            Location: https://api.packethost.net/projects/9317a146-bdb8-4d73-a59e-2cca97aaabbd rel="self"

  + Body

            {
              "href": "https://api.packethost.net/projects/9317a146-bdb8-4d73-a59e-2cca97aaabbd"
            }


## Project [/projects/{id}]
A single project object.

+ Parameters
  + id (string) ... The project ID (in the form of a UUID).

+ Model

        {
          "id": "75bd5fcb-dc4f-4f2b-8626-eaed6ee21ad1",
          "href": "https://api.packethost.net/projects/75bd5fcb-dc4f-4f2b-8626-eaed6ee21ad1",
          "name": "My Project",
          "members": [
            { "href": "https://api.packethost.net/users/0ad30f88-b3b5-46bf-a485-8132f858f8c8" },
            { "href": "https://api.packethost.net/users/9793d8a9-3e7e-487e-9042-78aa2f4e1d9d" },
            ...
          ],
          "memberships": [
            { "href": "https://api.packethost.net/memberships/e4db34df-bb03-43a1-bd46-3f91ade18ed4" },
            { "href": "https://api.packethost.net/memberships/bde083f5-67b6-4593-b3ee-e63ac3d7f79a" },
            ...
          ],
          "invitations": [
            { "href": "https://api.packethost.net/invitations/9aa3bd55-5209-42b6-9ed8-ec72ba043dba" }
          ],
          "devices": [ ... ],
          "payment_method": {
            "href": "https://api.packethost.net/payment-methods/27613a27-1169-49e7-aa04-6fde97702ba0"
          },
          "credits": [ ... ],
          "credit_total": 100,
          "default_for": "23a57279-8304-437d-9517-ebdbacf6413c",
          "created_at": "2014-04-14T02:15:15Z",
          "updated_at": "2014-04-28T01:18:50Z"
        }

### Retrieve a Project [GET]

+ Response 200

  [Project][]

### Update a Project [PATCH]

+ Request

  + Body

            {
              "name": "My Updated Project",
              "payment_method": "511a27d6-1066-4525-9fe5-53dc3b7f2f6f"
            }

+ Response 204

### Delete a Project [DELETE]
Deletes a device and de-provisions it in our datacenter.

+ Response 204

## Membership [/memberships/{id}]
A single membership record for a project.

A membership has the following parameters:

- id
- user
- project
- roles

+ Parameters
  + id (string) ... The membership ID.

+ Model

    {
      "id": "7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
      "href": "https://api.packethost.net/memberships/7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
      "project": { "href": "https://api.packethost.net/projects/591144ca-d479-407a-a4bc-042cda95a1d1" },
      "user": { "href": "https://api.packethost.net/users/2084e6f4-d7c0-4300-ab03-53830c9ddb01" },
      "owner": true,
      "roles": [ "collaborator", "billing" ],
      "created_at": "2014-09-29T15:14:34Z",
      "updated_at": "2014-10-01T09:34:12Z"
    }

### Retrieve a Membership [GET]
Returns a single membership object.

+ Response 200

  [Membership][]

### Update a Membership [PATCH]
Updates a membership record.

+ Request

  + Body

            {
              "roles": [ "collaborator" ]
            }

+ Response 204

### Delete a Membership [DELETE]
Deletes a membership record. This will remove the user from the project.

+ Response 204

## Invitations [/projects/{id}/invitations]
In order to add a user to a project, they must first be invited.

### Create a Project Invitation [POST]

+ Request

  + Body

            {
              "user": "3624b674-ca22-4bd6-a8d7-2090a2a2c15d",
              // or
              "user": "billy@example.com",

              "roles": [ "collaborator", "billing" ]
            }

+ Response 201

  + Headers

            Location: https://api.packethost.net/invitations/8738dd01-7246-443a-95b8-c8c493bd2c9b rel="self"

  + Body

            {
              "href": "https://api.packethost.net/invitations/8738dd01-7246-443a-95b8-c8c493bd2c9b"
            }

## Invitation [/invitations/{id}]
A single invitation record.

### View an Invitation [GET]

+ Response 200

  [Membership][]

### Accept an Invitation [PATCH]

+ Response 204

### Decline an Invitation [DELETE]

+ Response 204

## Transfer Requests [/projects/{id}/transfers]
Project owners can transfer ownership of their projects to other members.

### Create a Transfer Request [POST]

+ Response 201

  + Headers

            Location: https://api.packethost.net/transfers/1631425e-5a68-40c2-8075-8923ce306707 rel="self"

  + Body

            {
              "href": "https://api.packethost.net/transfers/1631425e-5a68-40c2-8075-8923ce306707"
            }

## Transfer Request [/transfers/{id}]
Accept or decline a transfer request.

+ Parameters
  + id (string) ... The membership ID.

+ Model

    {
      "id": "7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
      "href": "https://api.packethost.net/transfers/7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
      "project": { "href": "https://api.packethost.net/projects/591144ca-d479-407a-a4bc-042cda95a1d1" },
      "membership": { "href": "https://api.packethost.net/memberships/2084e6f4-d7c0-4300-ab03-53830c9ddb01" },
      "created_at": "2014-09-29T15:14:34Z",
      "updated_at": "2014-10-01T09:34:12Z"
    }

### View a Transfer Request [GET]

+ Response 200

  [Transfer Request][]

### Accept a Transfer Request [PATCH]

+ Response 204

### Decline a Transfer Request [DELETE]

+ Response 204
