# Group Projects
Projects are a way to group devices and grant users access to them.

## Projects [/projects]
A collection of projects that the current user is a member of.

### Retrieve all Projects [GET]
Returns a list of the current user's projects.

+ Response 200

  + Body

            {
              "projects": [
                {
                  "href": "https://api.packet.net/projects/739ff9c9-0834-44c8-bba6-6a71b9a96783",
                  "id": "739ff9c9-0834-44c8-bba6-6a71b9a96783",
                  "name": "A Test Project",
                  ...
                },
                {
                  "href": "https://api.packet.net/projects/74e70cdd-b51d-4d69-bf0c-ccf920643d7a",
                  "id": "74e70cdd-b51d-4d69-bf0c-ccf920643d7a",
                  "name": "My Second Project",
                  ...
                },
                ...
              ]
            }

### Create a Project [POST]
Creates a new projects and adds the current user as a member.

+ Request

  + Body

            {
              "name": "My New Project",
              "payment_method": "eedbb692-b217-477f-bfe5-8dd58df1cd09" // optional
            }

+ Response 201

  + Headers

            Location: https://api.packet.net/projects/9317a146-bdb8-4d73-a59e-2cca97aaabbd rel="self"

  + Body

            {
              "id": "9317a146-bdb8-4d73-a59e-2cca97aaabbd",
              "href": "/projects/9317a146-bdb8-4d73-a59e-2cca97aaabbd",
              "name": "My Project",
              "credit_amount": 0.0,
              "created_at": "2014-04-14T02:15:15Z",
              "updated_at": "2014-04-28T01:18:50Z",
              "max_devices": {
                "baremetal_1": 3,
                "baremetal_3": 1
              },
              "payment_method": {
                "href": "/payment-methods/eedbb692-b217-477f-bfe5-ba41d5c430c5"
              },
              "members": [
                { "href": "/users/0ad30f88-b3b5-46bf-a485-8132f858f8c8" },
                { "href": "/users/9793d8a9-3e7e-487e-9042-78aa2f4e1d9d" },
                ...
              ],
              "memberships": [
                { "href": "/memberships/e4db34df-bb03-43a1-bd46-3f91ade18ed4" },
                { "href": "/memberships/bde083f5-67b6-4593-b3ee-e63ac3d7f79a" },
                ...
              ],
              "invitations": [
                { "href": "/invitations/9aa3bd55-5209-42b6-9ed8-ec72ba043dba" }
              ],
              "devices": [
                { "href": "/devices/e66d2966-5209-42b6-9e96-251fc35fa9f6" },
                { "href": "/devices/4a7e65bd-da28-43d6-9fd0-fcb9103c8126" }
              ],
              "ssh_keys": [
                { "href": "/ssh-keys/07ca6c5e-d038-4c90-826a-16e03883dc47" },
                { "href": "/ssh-keys/ed632838-d2c7-4a88-91ff-ee9ce236e39d" }
              ]
            }


## Project [/projects/{id}]
A single project object.

+ Parameters
  + id (string) ... The project ID

+ Model

            {
              "id": "9317a146-bdb8-4d73-a59e-2cca97aaabbd",
              "href": "/projects/9317a146-bdb8-4d73-a59e-2cca97aaabbd",
              "name": "My Project",
              "credit_amount": 0.0,
              "created_at": "2014-04-14T02:15:15Z",
              "updated_at": "2014-04-28T01:18:50Z",
              "max_devices": {
                "baremetal_1": 3,
                "baremetal_3": 1
              },
              "payment_method": {
                "href": "/payment-methods/eedbb692-b217-477f-bfe5-ba41d5c430c5"
              },
              "members": [
                { "href": "/users/0ad30f88-b3b5-46bf-a485-8132f858f8c8" },
                { "href": "/users/9793d8a9-3e7e-487e-9042-78aa2f4e1d9d" },
                ...
              ],
              "memberships": [
                { "href": "/memberships/e4db34df-bb03-43a1-bd46-3f91ade18ed4" },
                { "href": "/memberships/bde083f5-67b6-4593-b3ee-e63ac3d7f79a" },
                ...
              ],
              "invitations": [
                { "href": "/invitations/9aa3bd55-5209-42b6-9ed8-ec72ba043dba" }
              ],
              "devices": [
                { "href": "/devices/e66d2966-5209-42b6-9e96-251fc35fa9f6" },
                { "href": "/devices/4a7e65bd-da28-43d6-9fd0-fcb9103c8126" }
              ],
              "ssh_keys": [
                { "href": "/ssh-keys/07ca6c5e-d038-4c90-826a-16e03883dc47" },
                { "href": "/ssh-keys/ed632838-d2c7-4a88-91ff-ee9ce236e39d" }
              ]
            }

### Retrieve a Project [GET]

+ Response 200

  [Project][]

### Update a Project [PATCH]

+ Request

  + Body

            {
              "name": "My Updated Project",
              "payment_method": "511a27d6-1066-4525-9fe5-53dc3b7f2f6f"
            }

+ Response 200

  [Project][]

### Delete a Project [DELETE]
Deletes a device and de-provisions it in our datacenter.

+ Response 204

## Events [/projects/{id}/events]
Provides a list of events for a single project.

### Retrieves an array of events [GET]

+ Parameters
  + id (string) ... The project ID.

+ Response 200

  + Body

            {
              "events": [
                {
                  "id": "60670752-25cd-426e-9faa-86a602ca4c90",
                  "type": "membership.created",
                  "body": "%user% is now a member of the project \"%project%\"",
                  "created_at": "2015-05-14T12:50:47Z",
                  "relationships": [
                    {
                      "id": "f6c0878f-4447-4543-9316-cddfa896107b"
                    },
                    {
                      "id": "1ff8f822-4864-45f5-95ed-7fe73a3091b7"
                    }
                  ],
                  "interpolated": "Dolly Example is now a member of the project \"Foo Bar Project\"",
                  "href": "/events/60670752-25cd-426e-9faa-86a602ca4c90"
                },
                ...
              ]
            }


## Membership [/memberships/{id}]
A single membership record for a project.

A membership has the following parameters:

- id
- user
- project
- roles

+ Parameters
  + id (string) ... The membership ID.

+ Model

        {
          "id": "7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
          "href": "https://api.packet.net/memberships/7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
          "project": { "href": "https://api.packet.net/projects/591144ca-d479-407a-a4bc-042cda95a1d1" },
          "user": { "href": "https://api.packet.net/users/2084e6f4-d7c0-4300-ab03-53830c9ddb01" },
          "owner": true,
          "roles": [ "collaborator", "billing" ],
          "created_at": "2014-09-29T15:14:34Z",
          "updated_at": "2014-10-01T09:34:12Z"
        }

### Retrieve a Membership [GET]
Returns a single membership object.

+ Response 200

  [Membership][]

### Update a Membership [PATCH]
Updates a membership record.

+ Request

  + Body

            {
              "roles": [ "collaborator" ]
            }

+ Response 204

### Delete a Membership [DELETE]
Deletes a membership record. This will remove the user from the project.

+ Response 204

## Invitations [/projects/{id}/invitations]
In order to add a user to a project, they must first be invited.

### Create a Project Invitation [POST]

+ Request

  + Body

            {
              "user": "3624b674-ca22-4bd6-a8d7-2090a2a2c15d",
              // or
              "user": "billy@example.com",
              "message": "Welcome to my project!",
              "roles": [ "collaborator", "billing" ]
            }

+ Response 201

  + Headers

            Location: https://api.packet.net/invitations/8738dd01-7246-443a-95b8-c8c493bd2c9b rel="self"

  + Body

            {
              "href": "https://api.packet.net/invitations/8738dd01-7246-443a-95b8-c8c493bd2c9b"
            }

## Invitation [/invitations/{id}]
A single invitation record.

### View an Invitation [GET]

+ Response 200

  [Membership][]

### Accept an Invitation [PATCH]

+ Response 204

### Decline an Invitation [DELETE]

+ Response 204

## Transfer Requests [/projects/{id}/transfers]
Project owners can transfer ownership of their projects to other members.

### Create a Transfer Request [POST]

+ Response 201

  + Headers

            Location: https://api.packet.net/transfers/1631425e-5a68-40c2-8075-8923ce306707 rel="self"

  + Body

            {
              "href": "https://api.packet.net/transfers/1631425e-5a68-40c2-8075-8923ce306707"
            }

## Transfer Request [/transfers/{id}]
Accept or decline a transfer request.

+ Parameters
  + id (string) ... The membership ID.

+ Model

        {
          "id": "7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
          "href": "https://api.packet.net/transfers/7a156b4f-cefb-4b94-a295-452c9e9fdb5f",
          "project": { "href": "https://api.packet.net/projects/591144ca-d479-407a-a4bc-042cda95a1d1" },
          "membership": { "href": "https://api.packet.net/memberships/2084e6f4-d7c0-4300-ab03-53830c9ddb01" },
          "created_at": "2014-09-29T15:14:34Z",
          "updated_at": "2014-10-01T09:34:12Z"
        }

### View a Transfer Request [GET]

+ Response 200

  [Transfer Request][]

### Accept a Transfer Request [PATCH]

+ Response 204

### Decline a Transfer Request [DELETE]

+ Response 204


## IP Reservations [/projects/{id}/ips]
Provides a list of IP resevations for a single project.

+ Parameter
  + id (string) ... The project ID.

### Retrieve all IP reservations [GET]

+ Response 200

  + Body

            [
              {
                "id": "174de894-01d3-45ba-b241-f24679d6f00c",
                "address": "147.75.193.9",
                "network": "147.75.193.9",
                "address_family": 4,
                "public":true,
                "cidr":32,
                "assignments": [
                                  { "href": "/ips/7ab2c92c-4db4-4bb5-aaac-471cb8cb55c4" },
                                  { "href": "/ips/ee783f17-4bd3-4798-893f-5c3d95e67b1c" }
                                ]
                ...
              },
              {
                "id": "174de894-01d3-45ba-b241-f24679d6f00d",
                "address": null,
                "network": "2604:1380:4:1300::",
                "address_family": 6,
                "public":false,
                "cidr":31,
                "assignments": [
                                  { "href": "/ips/7ab2c92c-4db4-4bb5-aaac-471cb8cb55c4" },
                                  { "href": "/ips/ee783f17-4bd3-4798-893f-5c3d95e67b1c" }
                                ]
                ...
              }
            ]

### Requesting IP reservations [POST]
Request more IP space for a project in order to have additional IP addresses to assign to devices

+ Request

  + Body

            {
              "type": "public_ipv4", // public_ipv4 || global_ipv4
              "quantity": 8, // How many IPv4 you want to request. Options: 1, 2, 4, 8, 16, 32, 64, 128, 256
              "comments": "This is my comment to the Packet team" // Optional comment
            }

+ Response 204

## IP Reservation [/ips/{id}]
See information about an IP address assignment.

+ Parameter
  + id (string) ... The IP reservation ID.

+ Model

        {
          "id": "3c29133a-d10c-4b86-86d4-69b9b16eadb5",
          "network": "75.72.66.16", // network address
          "address_family": 4, // 4 || 6 depending of the address family
          "netmask": "255.255.255.255",
          "public": true, // true for public IP reservation || false for private IP reservation
          "cidr": 32,
          "assignments": [
                            { "href": "/ips/7ab2c92c-4db4-4bb5-aaac-471cb8cb55c4" },
                            { "href": "/ips/ee783f17-4bd3-4798-893f-5c3d95e67b1c" }
                          ]
          "href": "/ips/3c29133a-d10c-4b86-86d4-69b9b16eadb5"
        }

### View an IP Reservation [GET]
Returns a single IP reservation object.

+ Response 200

  [IP Reservation][]

### Remove an IP Reservation [DELETE]
Remove an IP reservation from the project.

+ Response 204
