# Group Credits
Packet staff can issue credits to projects that take money of the project's
monthly balance. Credits are like gift certificates; they have an amount, and
each month the billing system will subtract from a project's credits until the
credit has run out before charging the user's payment method.

## Credit [/credits/{id}]
An account credit.

+ Model

        {
          "id": "7d624bbf-0070-45bc-b23d-185d580db585",
          "href": "https://api.packet.net/credits/7d624bbf-0070-45bc-b23d-185d580db585",
          "description": "For the downtime on 11/11/2014",
          "amount": 20,
          "remaining": 10,
          "project": {
            "href": "https://api.packet.net/projects/e27bcf46-ca98-40cf-b449-b89cea273fc8"
          },
          "created_at": "2014-12-04T12:00:00Z",
          "updated_at": "2014-12-04T12:00:00Z"
        }

### Retrieve a Credit [GET]
Get details about an account credit.

+ Response 200

  [Credit][]
