# Group Support
Manage support tickets.

## Tickets [/tickets]
A collection of support tickets that the current user has access to.

### Retrieve all Tickets [GET]
Returns a list of all tickets that the current user can access.

+ Response 200

  + Headers

            Link: https://api.packet.net/tickets?page=1&per_page=3; rel="previous", https://api.packet.net/tickets?page=3&per_page=3; rel="next"

  + Body

            {
              "tickets": [
                { "href": "https://api.packet.net/tickets/d50ba7a5-4714-4c98-a637-a08235191dec" },
                { "href": "https://api.packet.net/tickets/93a732e1-1130-47d9-bc52-3b6e759ec6f8" },
                { "href": "https://api.packet.net/tickets/4df0ae8b-d710-4e3a-8cfc-0565d96cd9bd" }
              ],
                "total": 300,
                "page": 2,
                "per_page": 3,
                "previous": "https://api.packet.net/tickets?page=1&per_page=3",
                "next": "https://api.packet.net/tickets?page=3&per_page=3"
            }

## Ticket [/tickets/{id}]
A single support ticket object.

+ Parameters
  + id (string) ... The ticket ID (in the form of a UUID).

### Retrieve a Ticket [GET]

+ Response 200

  + Body

            {
              "href": "https://api.packet.net/tickets/44db7032-b877-4355-802a-76a01e5f64f8",
              "id": "44db7032-b877-4355-802a-76a01e5f64f8",
              "open": true,
              "user": "test@packet.net",
              "assignee": "test@packet.net",
              "tickets": [ ... ],
              "body": "Hey Packetfolk, I tried to update my server the other day, but when I tried to ...",
              "created_at": "2014-08-20T22:03:00Z"
            }
