# Group SSH Keys
Manage your ssh keys.

## SSH Keys [/ssh-keys]
A collection of the user's ssh keys.

### Retrieve all SSH Keys [GET]
Returns an array of ssh keys.

+ Response 200

  + Body

            {
              "ssh_keys": [
                {
                  "id": "ded9047b-1872-467a-ab4a-ac042aafbbdc",
                  "label": "My Key Label",
                  "key": "ssh-rsa CACVB3NzaC1yc2EAAAADAQABAAABAQC...",
                  "fingerprint": "74:f6:47:91:78:a2:c7:1e:ef:73:c9:b3:17:ab:ec:c9",
                  "created_at": "2015-06-01T18:37:09Z",
                  "updated_at": "2015-06-01T18:38:45Z",
                  "user": {
                    "href": "/users/9e0acc49-cfe3-4a07-b3b1-a8a3135a6571"
                  },
                  "href": "/ssh-keys/ded9047b-1872-467a-ab4a-ac042aafbbdc"
                },
                ...
              ]
            }

### Create a SSH Key [POST]
Add a new ssh key for the current user.

+ Request

  + Body

            {
              "label":"My New SSH Key",
              "key":"ssh-rsa BBBBC4a99Eklf7..."
            }

+ Reponse 201

  + Headers

            Location: https://api.packet.net/ssh-keys/ded9047b-1872-467a-ab4a-ac042aafbbdc rel="self"

  + Body

            {
              "id": "ded9047b-1872-467a-ab4a-ac042aafbbdc",
              "label": "My New SSH Key",
              "key": "ssh-rsa BBBBC4a99Eklf7...",
              "fingerprint": "74:f6:47:91:78:a2:c7:1e:ef:73:c9:b3:17:ab:ec:c9",
              "created_at": "2015-06-01T18:37:09Z",
              "updated_at": "2015-06-01T18:38:45Z",
              "user": {
                "href": "/users/9e0acc49-cfe3-4a07-b3b1-a8a3135a6571"
              },
              "href": "/ssh-keys/ded9047b-1872-467a-ab4a-ac042aafbbdc"
            }

## SSH Key [/ssh-keys/{id}]
Returns a single ssh key object.				    

### Retrieve a SSH Key [GET]

+ Parameters
  + id (string) ... The ssh key ID to retrieve.

+ Response 200

  + Body

            {
              "id": "ded9047b-1872-467a-ab4a-ac042aafbbdc",
              "label": "My Key Label",
              "key": "ssh-rsa CACVB3NzaC1yc2EAAAADAQABAAABAQC...",
              "fingerprint": "74:f6:47:91:78:a2:c7:1e:ef:73:c9:b3:17:ab:ec:c9",
              "created_at": "2015-06-01T18:37:09Z",
              "updated_at": "2015-06-01T18:38:45Z",
              "user": {
                "href": "/users/9e0acc49-cfe3-4a07-b3b1-a8a3135a6571"
              },
              "href": "/ssh-keys/ded9047b-1872-467a-ab4a-ac042aafbbdc"
            }

### Update a SSH Key [PATCH]

+ Parameters
  + id (string) ... The ssh key ID to update.

+ Request

  + Body

            {
              "label":"My new label",
              "key": "ssh-rsa CACVB3NzaC1yc2EAAAADAQABAAABAQC..."
            }

+ Response 200

  + Body

            {
              "id": "ded9047b-1872-467a-ab4a-ac042aafbbdc",
              "label": "My new label",
              "key": "ssh-rsa CACVB3NzaC1yc2EAAAADAQABAAABAQC...",
              "fingerprint": "74:f6:47:91:78:a2:c7:1e:ef:73:c9:b3:17:ab:ec:c9",
              "created_at": "2015-06-01T18:37:09Z",
              "updated_at": "2015-06-01T18:38:45Z",
              "user": {
                "href": "/users/9e0acc49-cfe3-4a07-b3b1-a8a3135a6571"
              },
              "href": "/ssh-keys/ded9047b-1872-467a-ab4a-ac042aafbbdc"
            }

### Delete a SSH Key [DELETE]
Delete a SSH Key.

+ Parameters
  + id (string) ... The ssh key ID to delete.

+ Response 204