# Group Notifications
Notifications are events that happen in the system that we want to let you know about. Like when a user is added to an organization, for example.

## Notifications [/notifications{?all,since}]
A collection of the current user's notifications.

### Retrieve all Notifications [GET]
Returns a list of the current user's notifications.

+ Parameters
  + all = `false` (optional, boolean) ... Whether to include read notification in the listing.
  + since = `Time.now` (optional, string) ... Only include notifications updated since the given datetime. Must be a UTC datetime in ISO8601 format.

+ Response 200

## Notification [/notifications/{id}]

A single notification object.

A notification has the following properties:

- id
- body
- read
- user
- created_at
- updated_at

+ Parameters
  + id (string) ... The notification ID in the form of a UUID.

+ Model

        {
          "id": "566ccde0-4347-11e4-826c-48d705c8e127",
          "body": "This is a test notification",
          "read": false,
          "user": {
            "href": "/users/76aff050-4347-11e4-9bf7-48d705c8e127"
          },
          "created_at": "2014-04-14T02:15:15Z",
          "updated_at": "2014-04-15T05:23:13Z"
        }


### Retrieve a Notification [GET]

+ Response 200

  [Notification][]

### Update a Notification [PATCH]
Updates a single notification. Currently, the only supported operating is
marking a notification as read.

+ Request

  + Body

            {
              "read": true
            }

+ Response 204
